<a href="https://colab.research.google.com/github/chaeeuen/python-machine-learing/blob/main/3_11_ESAA_%EA%B3%BC%EC%A0%9C%EC%88%98%EC%A0%95%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **판다스 (PANDAS)**

- `index` : 개별 데이터를 고유하개 식별하는 key 값
- `Series` : 칼럼이 하나 뿐인 데이터 구조체
- `DataFrame` : 칼럼이 여러 개인 데이터 구조체

## 1. 판다스 시작 - 파일을 DataFrame으로 로딩, 기본 API

  - `read_csv()` : csv 포맷변환 API, 콤마(,)로 칼럼 구분,  ()안에 sep= 에 구분문자 넣으면 됨. 별다른 파라미터 지정이 없다면 맨 처음 로우를 칼럼명으로 인지하고 칼럼으로 변환.
  - `read_table()` : 탭(\t)로 칼럼 구분.
  - `read_fwf()` : 고정길이 기반의 칼럼 포맷을 DataFrame으로 로딩하기 위한 API.


  1) DataFrame의 메타데이터 조회하기
  
  - `.shape()` : 행과 열의 크기 파악
  - `.info()` : 총 데이터 건수와 데이터 타입, NULL 건수 확인
  - `.describe()` : 칼럼형 숫자형 데이터 값의 n-percentile 분포도, 평균값, 최댓값, 최솟값 나타냄. 오직 숫자형(int) 칼럼의 분포도만 조사.
  - `.value_counts()` : 해당 칼럼값의 유형과 건수 확인가능.
  - `(dropna=False)`: NULL 값을 포함하여 value_counts() 적용시. 디폴트는 True(포함x).

## 2. DataFrame과 리스트, 딕셔너리, 넘파이 ndarray 상호 변환


1) 넘파이 ndarray, 리스트, 딕셔너리를 DataFrame으로 변환하기

- ndarray -> DataFrame : 칼럼명 1개 필요.

2) DataFrame을 ndarray, 리스트, 딕셔너리로 변환하기

- DataFrame -> ndarray : `.values`
- DataFrame -> 리스트 : `.values.tolist()`
- DataFrame -> 딕셔너리 : `.to_dict()`


## 3. DataFrame의 칼럼 데이터 세트 생성과 수정

- DataFrame[ ] 내에 새로운 칼럼명 입력 후 값 할당.

## 4. DataFrame 데이터 삭제

- `drop()`
       1) axis : axis=0 -> 로우방향축, axis=1 -> 칼럼방향축
       2) Inplace = False : 자기자신의 DataFrame의 데이터는 삭제하지 않으며, 삭제된 결과 DataFrame을 반환, Inplace=True면 자신의 DataFrame의 데이터를 삭제.


## 5. Index 객체

- `.index` : 인덱스 추출가능
- `reset_index()` : 새롭게 인덱스를 연속 숫자형으로 할당, 기존 인덱스는 'index'라는 새로운 칼럼명으로 추가


## 6. 데이터 셀렉션 및 필터링

1) DataFrame의 `[]` 연산자 : 칼럼명 문자, 인덱스로 변환가능한 문자식(칼럼지정 연산자)만 들어갈 수 있음. 불린 인덱싱 표현도 가능.

2) DataFrame `iloc[]` 연산자 : 위치기반 인덱싱만 허용. 행과 열의 좌표위치에 해당하는 값으로 정숫값 또는 정수형의 슬라이싱, 팬시리스트 값을 입력해야함. 인덱스값이나 칼럼명을 입력하면 오류.

- 열 위치에 -1을 입력하여 DataFrame의 가장 마지막 열 데이터 가져옴
- iloc[:,-1] : 맨 마지막 칼럼의 값 (타깃값)
- iloc[:,:-1] : 처음부터 맨 마지막 칼럼을 제외한 모든 칼럼의 값 (피처값)

3) DataFrame `loc[]` 연산자 : 명칭기반 데이터 추출, 행위치에는 인덱스값, 열 위치에는 칼럼명 입력.

- loc[]에 슬라이싱 기호를 적용하면 종료값 -1이 아니라 종료값까지 포함함. !!

4) 불린 인덱싱
- [], loc[] 에서 공통으로 지원. iloc[]는 정수형 값이 아닌 불린값에 대해서는 지원 x, 불린인덱싱 지원 x.
- []내에 불린 인덱싱을 적용하면 반환되는 객체가 DataFrame이므로 원하는 칼럼명만 별도로 추출가능.

## 7. 정렬, Aggregation 함수, GroupBy 적용

1) DataFrame, Series의 정렬 - sort_values()
- `by` : by로 특정칼럼을 입력하면 해당 칼럼으로 정렬을 수행. ascending = True 로 설정하면 오름차순 정렬. ascending = False 로 설정하면 내림차순으로 정렬. 기본은 True.
- `inplcae = False` : inplcae = False로 설정하면 sort_values()를 호출한 DataFrame은 그대로 유지하며 정렬된 DataFrame을 결과로 반환. inplace = True로 설정하면 호출한 DataFrame의 정렬결과를 그대로 적용. 기본은 inplace = False.

2) Aggregation 함수 적용
- DataFrame의 경우 DataFrame에서 바로 aggregation을 호출할 경우 모든 칼럼에 해당 aggregation을 적용함.
- 특정 컬럼에 aggregation 함수를 적용하기 위해서는 DataFrame에 대상 칼럼들만 추출해 aggregation을 적용하면 됨.
- `min()`, `max()`, `sum()`, `count()`

3) groupby() 적용
- 입력 파라미터 by에 칼럼을 입력하면 대상 칼럼으로 groupby 됨.
- DataFrame에 groupby()를 호출해 반환된 결과에 aggregation함수를 호출하면 groupby() 대상 칼럼을 제외한 모든 칼럼에 해당 aggregation 함수를 적용.

## 8. 결손 데이터 처리하기
1) `isna()`로 결손 데이터 여부 확인
- 모든 칼럼의 값이 NaN인지 아닌지를 True나 False로 알려줌.
- 결손 데이터의 개수는 `isna()` 결과에 sum() 함수를 추가해 구할 수 있음. `sum()` 호출 시 True는 1로, False는 0으로 변환.

2) `fillna()`로 결손 데이터 대체하기
- fillna()를 이용해 반환값을 다시 받거나 inplace=True 파라미터를 fillna()에 추가해야 실제 데이터 세트값이 변경됨.

## 9. apply lambda 식으로 데이터 가공
- 복잡한 데이터 가공이 필요할 경우 어쩔 수 없이 apply lambda를 이용.

In [11]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')
titanic_df = pd.read_csv('/content/drive/MyDrive/titanic_train.csv')
titanic_df.head(3)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [12]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [13]:
titanic_df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [14]:
value_counts = titanic_df['Pclass'].value_counts()
print(value_counts)

titanic_pclass = titanic_df['Pclass']
print(type(titanic_pclass))
titanic_pclass.head()

value_counts = titanic_df['Pclass'].value_counts()
print(type(value_counts))
print(value_counts)

3    491
1    216
2    184
Name: Pclass, dtype: int64
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
3    491
1    216
2    184
Name: Pclass, dtype: int64

In [15]:
import numpy as np
col_name1=['col1']
list1=[1,2,3]
array1=np.array(list1)
print('array1 shape :', array1.shape)
df_list1= pd.DataFrame(list1, columns=col_name1)
print(df_list1)
df_array1=pd.DataFrame(array1, columns=col_name1)
print(df_array1)

array1 shape : (3,)
   col1
0     1
1     2
2     3
   col1
0     1
1     2
2     3

In [16]:
col_name2=['col1','col2','col3']
list2 = [[1,2,3],[11,12,13]]

array2= np.array(list2)
print(array2.shape)
df_list2=pd.DataFrame(list2, columns=col_name2)
print(df_list2)
df_array2=pd.DataFrame(array2, columns=col_name2)
print(df_array2)

(2, 3)
   col1  col2  col3
0     1     2     3
1    11    12    13
   col1  col2  col3
0     1     2     3
1    11    12    13

In [17]:
dict={'col1':[1,11], 'col2':[2,22], 'col3':[3,33]}
df_dict = pd.DataFrame(dict)
array3= df_dict.values
print(type(array3), array3.shape)

list3=df_dict.values.tolist()
print(type(list3))
print(list3)

dict3= df_dict.to_dict('list')
print(type(dict3))
print(dict3)

<class 'numpy.ndarray'> (2, 3)
<class 'list'>
[[1, 2, 3], [11, 22, 33]]
<class 'dict'>
{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}

In [18]:
titanic_df['Age_0']=0
titanic_df.head(3)
titanic_df['Age_by_10']=titanic_df['Age']*10
titanic_df['Family_No']= titanic_df['SibSp']+titanic_df['Parch']+1
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0,Age_by_10,Family_No
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,220.0,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,380.0,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,260.0,1

In [19]:

pd.set_option('display.width',1000)
pd.set_option('display.max_colwidth',15)
print(titanic_df.head(3))

titanic_df.drop([0,1,2],axis=0, inplace=True)
print(titanic_df.head(3))


indexes = titanic_df.index
print(indexes)
print(indexes.values)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked  Age_0  Age_by_10  Family_No
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S      0      220.0          2
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C      0      380.0          2
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S      0      260.0          1
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked  Age_0  Age_by_10  Family_No
3            4         1       1  Futrelle, M...  female  35.0      1      0  113803  53.1000  C123        S      0      350.0          2
4            5         0       3  Allen, Mr. ...    male  35.0      0      0  373450   8.0500   NaN        S      0      350.0          1
5            6         0       3  Moran, Mr. ...    male   NaN      0      0  330877   8.4583   NaN        Q      0        NaN          1
RangeIndex(start=3, stop=891, step=1)
[  3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20
  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38
  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56
  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74
  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92
  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108 109 110
 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128
 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146
 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164
 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182
 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200
 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218
 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236
 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252 253 254
 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270 271 272
 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287 288 289 290
 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305 306 307 308
 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323 324 325 326
 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341 342 343 344
 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359 360 361 362
 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377 378 379 380
 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395 396 397 398
 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414 415 416
 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431 432 433 434
 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449 450 451 452
 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467 468 469 470
 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485 486 487 488
 489 490 491 492 493 494 495 496 497 498 499 500 501 502 503 504 505 506
 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521 522 523 524
 525 526 527 528 529 530 531 532 533 534 535 536 537 538 539 540 541 542
 543 544 545 546 547 548 549 550 551 552 553 554 555 556 557 558 559 560
 561 562 563 564 565 566 567 568 569 570 571 572 573 574 575 576 577 578
 579 580 581 582 583 584 585 586 587 588 589 590 591 592 593 594 595 596
 597 598 599 600 601 602 603 604 605 606 607 608 609 610 611 612 613 614
 615 616 617 618 619 620 621 622 623 624 625 626 627 628 629 630 631 632
 633 634 635 636 637 638 639 640 641 642 643 644 645 646 647 648 649 650
 651 652 653 654 655 656 657 658 659 660 661 662 663 664 665 666 667 668
 669 670 671 672 673 674 675 676 677 678 679 680 681 682 683 684 685 686
 687 688 689 690 691 692 693 694 695 696 697 698 699 700 701 702 703 704
 705 706 707 708 709 710 711 712 713 714 715 716 717 718 719 720 721 722
 723 724 725 726 727 728 729 730 731 732 733 734 735 736 737 738 739 740
 741 742 743 744 745 746 747 748 749 750 751 752 753 754 755 756 757 758
 759 760 761 762 763 764 765 766 767 768 769 770 771 772 773 774 775 776
 777 778 779 780 781 782 783 784 785 786 787 788 789 790 791 792 793 794
 795 796 797 798 799 800 801 802 803 804 805 806 807 808 809 810 811 812
 813 814 815 816 817 818 819 820 821 822 823 824 825 826 827 828 829 830
 831 832 833 834 835 836 837 838 839 840 841 842 843 844 845 846 847 848
 849 850 851 852 853 854 855 856 857 858 859 860 861 862 863 864 865 866
 867 868 869 870 871 872 873 874 875 876 877 878 879 880 881 882 883 884
 885 886 887 888 889 890]

In [20]:
print(type(indexes.values))
print(indexes.values.shape)
print(indexes[:5].values)
print(indexes.values[:5])
print(indexes[6])

indexes[0]=5

<class 'numpy.ndarray'>
(888,)
[3 4 5 6 7]
[3 4 5 6 7]
9

TypeError: Index does not support mutable operations

In [21]:
series_fair = titanic_df['Fare']
print(series_fair.max())
print(series_fair.sum())
print(sum(series_fair))
print('Fair Series +3:\n', (series_fair +3).head(3))

512.3292
28607.491
28607.49099999997
Fair Series +3:
 3    56.1000
4    11.0500
5    11.4583
Name: Fare, dtype: float64

In [22]:
titanic_reset_df = titanic_df.reset_index(inplace=False)
titanic_reset_df.head(3)

   index  PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked  Age_0  Age_by_10  Family_No
0      3            4         1       1  Futrelle, M...  female  35.0      1      0  113803  53.1000  C123        S      0      350.0          2
1      4            5         0       3  Allen, Mr. ...    male  35.0      0      0  373450   8.0500   NaN        S      0      350.0          1
2      5            6         0       3  Moran, Mr. ...    male   NaN      0      0  330877   8.4583   NaN        Q      0        NaN          1

In [23]:
value_counts =titanic_df['Pclass'].value_counts()
print(value_counts)
new_value_counts = value_counts.reset_index(inplace=False)
print(new_value_counts)
print(type(new_value_counts))

3    489
1    215
2    184
Name: Pclass, dtype: int64
   index  Pclass
0      3     489
1      1     215
2      2     184
<class 'pandas.core.frame.DataFrame'>

In [24]:
print(titanic_df['Pclass'].head(3))
print(titanic_df[['Survived','Pclass']].head(3))
print(titanic_df[0])

3    1
4    3
5    3
Name: Pclass, dtype: int64
   Survived  Pclass
3         1       1
4         0       3
5         0       3

KeyError: 0

In [25]:
titanic_df[0:2]

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket   Fare Cabin Embarked  Age_0  Age_by_10  Family_No
3            4         1       1  Futrelle, M...  female  35.0      1      0  113803  53.10  C123        S      0      350.0          2
4            5         0       3  Allen, Mr. ...    male  35.0      0      0  373450   8.05   NaN        S      0      350.0          1

In [26]:
titanic_df[titanic_df['Pclass']==3].head(3)

   PassengerId  Survived  Pclass            Name   Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked  Age_0  Age_by_10  Family_No
4            5         0       3  Allen, Mr. ...  male  35.0      0      0  373450   8.0500   NaN        S      0      350.0          1
5            6         0       3  Moran, Mr. ...  male   NaN      0      0  330877   8.4583   NaN        Q      0        NaN          1
7            8         0       3  Palsson, Ma...  male   2.0      3      1  349909  21.0750   NaN        S      0       20.0          5

In [27]:
data = {'Name': ['Chulmin', 'Eunkyung','Jinwoong','Soobeom'],
        'Year': [2011, 2016, 2015, 2015],
        'Gender': ['Male', 'Female', 'Male', 'Male']
       }
data_df = pd.DataFrame(data, index=['one','two','three','four'])
data_df

           Name  Year  Gender
one     Chulmin  2011    Male
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male
four    Soobeom  2015    Male

In [28]:
data_df.iloc[0,0]

'Chulmin'

In [29]:
data_df.iloc[0, 'Name']

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

In [30]:
print(data_df.iloc[:,-1])
print(data_df.iloc[:,:-1])
data_df.loc['one','Name']
data_df.loc[0,'Name']
print(data_df.iloc[0:1,0],'\n')
print(data_df.loc['one','two','Name'])

one        Male
two      Female
three      Male
four       Male
Name: Gender, dtype: object
           Name  Year
one     Chulmin  2011
two    Eunkyung  2016
three  Jinwoong  2015
four    Soobeom  2015

KeyError: 0

In [31]:
titanic_boolean = titanic_df[titanic_df['Age'] > 60]
print(type(titanic_boolean))
titanic_boolean

<class 'pandas.core.frame.DataFrame'>

     PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch       Ticket      Fare        Cabin Embarked  Age_0  Age_by_10  Family_No
33            34         0       2  Wheadon, Mr...    male  66.0      0      0   C.A. 24579   10.5000          NaN        S      0      660.0          1
54            55         0       1  Ostby, Mr. ...    male  65.0      0      1       113509   61.9792          B30        C      0      650.0          2
96            97         0       1  Goldschmidt...    male  71.0      0      0     PC 17754   34.6542           A5        C      0      710.0          1
116          117         0       3  Connors, Mr...    male  70.5      0      0       370369    7.7500          NaN        Q      0      705.0          1
170          171         0       1  Van der hoe...    male  61.0      0      0       111240   33.5000          B19        S      0      610.0          1
252          253         0       1  Stead, Mr. ...    male  62.0      0      0       113514   26.5500          C87        S      0      620.0          1
275          276         1       1  Andrews, Mi...  female  63.0      1      0        13502   77.9583           D7        S      0      630.0          2
280          281         0       3  Duane, Mr. ...    male  65.0      0      0       336439    7.7500          NaN        Q      0      650.0          1
326          327         0       3  Nysveen, Mr...    male  61.0      0      0       345364    6.2375          NaN        S      0      610.0          1
438          439         0       1  Fortune, Mr...    male  64.0      1      4        19950  263.0000  C23 C25 C27        S      0      640.0          6
456          457         0       1  Millet, Mr....    male  65.0      0      0        13509   26.5500          E38        S      0      650.0          1
483          484         1       3  Turkula, Mr...  female  63.0      0      0         4134    9.5875          NaN        S      0      630.0          1
493          494         0       1  Artagaveyti...    male  71.0      0      0     PC 17609   49.5042          NaN        C      0      710.0          1
545          546         0       1  Nicholson, ...    male  64.0      0      0          693   26.0000          NaN        S      0      640.0          1
555          556         0       1  Wright, Mr....    male  62.0      0      0       113807   26.5500          NaN        S      0      620.0          1
570          571         1       2  Harris, Mr....    male  62.0      0      0  S.W./PP 752   10.5000          NaN        S      0      620.0          1
625          626         0       1  Sutton, Mr....    male  61.0      0      0        36963   32.3208          D50        S      0      610.0          1
630          631         1       1  Barkworth, ...    male  80.0      0      0        27042   30.0000          A23        S      0      800.0          1
672          673         0       2  Mitchell, M...    male  70.0      0      0   C.A. 24580   10.5000          NaN        S      0      700.0          1
745          746         0       1  Crosby, Cap...    male  70.0      1      1    WE/P 5735   71.0000          B22        S      0      700.0          3
829          830         1       1  Stone, Mrs....  female  62.0      0      0       113572   80.0000          B28      NaN      0      620.0          1
851          852         0       3  Svensson, M...    male  74.0      0      0       347060    7.7750          NaN        S      0      740.0          1

In [32]:
titanic_df[titanic_df['Age'] > 60][['Name','Age']].head(3)
titanic_df.loc[titanic_df['Age'] > 60, ['Name','Age']].head(3)
titanic_df[ (titanic_df['Age'] > 60) & (titanic_df['Pclass']==1) & (titanic_df['Sex']=='female')]

cond1 = titanic_df['Age'] > 60
cond2 = titanic_df['Pclass']==1
cond3 = titanic_df['Sex']=='female'
titanic_df[ cond1 & cond2 & cond3]

     PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked  Age_0  Age_by_10  Family_No
275          276         1       1  Andrews, Mi...  female  63.0      1      0   13502  77.9583    D7        S      0      630.0          2
829          830         1       1  Stone, Mrs....  female  62.0      0      0  113572  80.0000   B28      NaN      0      620.0          1

In [33]:
titanic_sorted = titanic_df.sort_values(by=['Name'])
titanic_sorted.head(3)
titanic_sorted = titanic_df.sort_values(by=['Pclass', 'Name'], ascending=False)
titanic_sorted.head(3)

     PassengerId  Survived  Pclass            Name   Sex   Age  SibSp  Parch    Ticket  Fare Cabin Embarked  Age_0  Age_by_10  Family_No
868          869         0       3  van Melkebe...  male   NaN      0      0    345777   9.5   NaN        S      0        NaN          1
153          154         0       3  van Billiar...  male  40.5      0      2  A/5. 851  14.5   NaN        S      0      405.0          3
282          283         0       3  de Pelsmaek...  male  16.0      0      0    345778   9.5   NaN        S      0      160.0          1

In [34]:
titanic_df.count()

PassengerId    888
Survived       888
Pclass         888
Name           888
Sex            888
Age            711
SibSp          888
Parch          888
Ticket         888
Fare           888
Cabin          203
Embarked       886
Age_0          888
Age_by_10      711
Family_No      888
dtype: int64

In [35]:
titanic_df[['Age', 'Fare']].mean()

Age     29.703474
Fare    32.215643
dtype: float64

In [36]:
titanic_groupby = titanic_df.groupby(by='Pclass')
print(type(titanic_groupby))

titanic_groupby = titanic_df.groupby('Pclass').count()
titanic_groupby

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>

        PassengerId  Survived  Name  Sex  Age  SibSp  Parch  Ticket  Fare  Cabin  Embarked  Age_0  Age_by_10  Family_No
Pclass
1               215       215   215  215  185    215    215     215   215    175       213    215        185        215
2               184       184   184  184  173    184    184     184   184     16       184    184        173        184
3               489       489   489  489  353    489    489     489   489     12       489    489        353        489

In [37]:
titanic_groupby = titanic_df.groupby('Pclass')[['PassengerId', 'Survived']].count()
titanic_groupby

        PassengerId  Survived
Pclass
1               215       215
2               184       184
3               489       489

In [38]:
titanic_df.groupby('Pclass')['Age'].agg([max, min])

         max   min
Pclass
1       80.0  0.92
2       70.0  0.67
3       74.0  0.42

In [39]:
agg_format={'Age':'max', 'SibSp':'sum', 'Fare':'mean'}
titanic_df.groupby('Pclass').agg(agg_format)

         Age  SibSp       Fare
Pclass
1       80.0     89  84.214554
2       70.0     74  20.662183
3       74.0    301  13.700450

In [40]:
titanic_df.isna().head(3)

   PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket   Fare  Cabin  Embarked  Age_0  Age_by_10  Family_No
3        False     False   False  False  False  False  False  False   False  False  False     False  False      False      False
4        False     False   False  False  False  False  False  False   False  False   True     False  False      False      False
5        False     False   False  False  False   True  False  False   False  False   True     False  False       True      False

In [42]:
titanic_df.isna( ).sum( )

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          685
Embarked         2
Age_0            0
Age_by_10      177
Family_No        0
dtype: int64

In [43]:
titanic_df['Cabin'] = titanic_df['Cabin'].fillna('C000')
titanic_df.head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked  Age_0  Age_by_10  Family_No
3            4         1       1  Futrelle, M...  female  35.0      1      0  113803  53.1000  C123        S      0      350.0          2
4            5         0       3  Allen, Mr. ...    male  35.0      0      0  373450   8.0500  C000        S      0      350.0          1
5            6         0       3  Moran, Mr. ...    male   NaN      0      0  330877   8.4583  C000        Q      0        NaN          1

In [44]:
titanic_df['Age'] = titanic_df['Age'].fillna(titanic_df['Age'].mean())
titanic_df['Embarked'] = titanic_df['Embarked'].fillna('S')
titanic_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin            0
Embarked         0
Age_0            0
Age_by_10      177
Family_No        0
dtype: int64

In [45]:
def get_square(a):
  return a**2

print('3의 제곱은:',get_square(3))

3의 제곱은: 9

In [46]:
lambda_square = lambda x : x ** 2
print('3의 제곱은:',lambda_square(3))

3의 제곱은: 9

In [47]:
a=[1,2,3]
squares = map(lambda x : x**2, a)
list(squares)

[1, 4, 9]

In [48]:
titanic_df['Name_len']= titanic_df['Name'].apply(lambda x : len(x))
titanic_df[['Name','Name_len']].head(3)

             Name  Name_len
3  Futrelle, M...        44
4  Allen, Mr. ...        24
5  Moran, Mr. ...        16

In [49]:
titanic_df['Child_Adult'] = titanic_df['Age'].apply(lambda x : 'Child' if x <=15 else 'Adult' )
titanic_df[['Age','Child_Adult']].head(8)

          Age Child_Adult
3   35.000000       Adult
4   35.000000       Adult
5   29.703474       Adult
6   54.000000       Adult
7    2.000000       Child
8   27.000000       Adult
9   14.000000       Child
10   4.000000       Child

In [50]:
titanic_df['Age_cat'] = titanic_df['Age'].apply(lambda x : 'Child' if x<=15 else ('Adult' if x <= 60 else 'Elderly'))
titanic_df['Age_cat'].value_counts()

Adult      783
Child       83
Elderly     22
Name: Age_cat, dtype: int64

In [51]:
def get_category(age):
    cat = ''
    if age <= 5: cat = 'Baby'
    elif age <= 12: cat = 'Child'
    elif age <= 18: cat = 'Teenager'
    elif age <= 25: cat = 'Student'
    elif age <= 35: cat = 'Young Adult'
    elif age <= 60: cat = 'Adult'
    else : cat = 'Elderly'

    return cat

titanic_df['Age_cat'] = titanic_df['Age'].apply(lambda x : get_category(x))
titanic_df[['Age','Age_cat']].head()

         Age      Age_cat
3  35.000000  Young Adult
4  35.000000  Young Adult
5  29.703474  Young Adult
6  54.000000        Adult
7   2.000000         Baby